version: 1.0.{build}
image: Visual Studio 2019 Preview
environment:
  matrix:
    - LINKAGE: static
      RUNTIME_LIBRARY: MT
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
      LICENSE: LGPL21

matrix:
  fast_finish: true
platform:
  - x64
configuration: Release
install: install.bat
build_script: build.bat
test: off
artifacts:
  - path: '*.zip'
  - path: '*.7z'
deploy:
  description: 'Headers, libraries, and executables for FFmpeg.'
  provider: GitHub
  auth_token:
    secure: QSdxjkooPHApqh95gD9duaZBxmv/5zWzDcukjNQGmbedwEu0BvzgA6HUEXpvni25
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
cache:
  - c:\nasm-2.14.03rc2-win64.zip
